
_**PROJECT DESCRIPTION**_

In this project we have two different ofdata sets: one of them shows the video game salesin Europien Union, North America, Japan,, other countries and Globalsales for every videogame individually. Also giving us information about Genre, te year video game relased and the publisher.

The other data set is the GBT

In [62]:
import pandas as pd
!pip install pandas openpyxl


url = "C:\\Users\\admin\\Desktop\\vgsales.csv"
df_game = pd.read_csv(url)

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: openpyxl in c:\users\admin\anaconda3\lib\site-packages (3.0.10)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: et_xmlfile in c:\users\admin\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [21]:
df_game.head(50)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31
10,11,Nintendogs,DS,2005.0,Simulation,Nintendo,9.07,11.00,1.93,2.75,24.76
11,12,Mario Kart DS,DS,2005.0,Racing,Nintendo,9.81,7.57,4.13,1.92,23.42
12,13,Pokemon Gold/Pokemon Silver,GB,1999.0,Role-Playing,Nintendo,9.00,6.18,7.20,0.71,23.10
13,14,Wii Fit,Wii,2007.0,Sports,Nintendo,8.94,8.03,3.60,2.15,22.72
14,15,Wii Fit Plus,Wii,2009.0,Sports,Nintendo,9.09,8.59,2.53,1.79,22.00
15,16,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
18,19,Super Mario World,SNES,1990.0,Platform,Nintendo,12.78,3.75,3.54,0.55,20.61
19,20,Brain Age: Train Your Brain in Minutes a Day,DS,2005.0,Misc,Nintendo,4.75,9.26,4.16,2.05,20.22
20,21,Pokemon Diamond/Pokemon Pearl,DS,2006.0,Role-Playing,Nintendo,6.42,4.52,6.04,1.37,18.36
21,22,Super Mario Land,GB,1989.0,Platform,Nintendo,10.83,2.71,4.18,0.42,18.14
22,23,Super Mario Bros. 3,NES,1988.0,Platform,Nintendo,9.54,3.44,3.84,0.46,17.28
23,24,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
24,25,Grand Theft Auto: Vice City,PS2,2002.0,Action,Take-Two Interactive,8.41,5.49,0.47,1.78,16.15
25,26,Pokemon Ruby/Pokemon Sapphire,GBA,2002.0,Role-Playing,Nintendo,6.06,3.90,5.38,0.50,15.85
26,27,Pokemon Black/Pokemon White,DS,2010.0,Role-Playing,Nintendo,5.57,3.28,5.65,0.82,15.32
27,28,Brain Age 2: More Training in Minutes a Day,DS,2005.0,Puzzle,Nintendo,3.44,5.36,5.32,1.18,15.30
28,29,Gran Turismo 3: A-Spec,PS2,2001.0,Racing,Sony Computer Entertainment,6.85,5.09,1.87,1.16,14.98
29,30,Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
30,31,Pokémon Yellow: Special Pikachu Edition,GB,1998.0,Role-Playing,Nintendo,5.89,5.04,3.12,0.59,14.64
31,32,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.67,3.73,0.11,1.13,14.64
32,33,Pokemon X/Pokemon Y,3DS,2013.0,Role-Playing,Nintendo,5.17,4.05,4.34,0.79,14.35
33,34,Call of Duty: Black Ops 3,PS4,2015.0,Shooter,Activision,5.77,5.81,0.35,2.31,14.24
34,35,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.88,0.65,2.52,14.03
35,36,Call of Duty: Black Ops II,X360,2012.0,Shooter,Activision,8.25,4.30,0.07,1.12,13.73
36,37,Call of Duty: Modern Warfare 2,X360,2009.0,Shooter,Activision,8.52,3.63,0.08,1.29,13.51
37,38,Call of Duty: Modern Warfare 3,PS3,2011.0,Shooter,Activision,5.54,5.82,0.49,1.62,13.46
38,39,Grand Theft Auto III,PS2,2001.0,Action,Take-Two Interactive,6.99,4.51,0.30,1.30,13.10
39,40,Super Smash Bros. Brawl,Wii,2008.0,Fighting,Nintendo,6.75,2.61,2.66,1.02,13.04
40,41,Call of Duty: Black Ops,PS3,2010.0,Shooter,Activision,5.98,4.44,0.48,1.83,12.73
41,42,Animal Crossing: Wild World,DS,2005.0,Simulation,Nintendo,2.55,3.52,5.33,0.88,12.27
42,43,Mario Kart 7,3DS,2011.0,Racing,Nintendo,4.74,3.91,2.67,0.89,12.21
43,44,Halo 3,X360,2007.0,Shooter,Microsoft Game Studios,7.97,2.83,0.13,1.21,12.14
44,45,Grand Theft Auto V,PS4,2014.0,Action,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98
45,46,Pokemon HeartGold/Pokemon SoulSilver,DS,2009.0,Action,Nintendo,4.40,2.77,3.96,0.77,11.90
46,47,Super Mario 64,N64,1996.0,Platform,Nintendo,6.91,2.85,1.91,0.23,11.89
47,48,Gran Turismo 4,PS2,2004.0,Racing,Sony Computer Entertainment,3.01,0.01,1.10,7.53,11.66
48,49,Super Mario Galaxy,Wii,2007.0,Platform,Nintendo,6.16,3.40,1.20,0.76,11.52
49,50,Pokemon Omega Ruby/Pokemon Alpha Sapphire,3DS,2014.0,Role-Playing,Nintendo,4.23,3.37,3.08,0.65,11.33

In [22]:
df_game['Platform'].unique()
#How many different platform is compared in dataframe.

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne', 'GC',
       'WiiU', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

In [23]:
smallest_year = df_game['Year'].min()

In [24]:
smallest_year 
#This is the year we start to get GDP VALUES for europe, japan, north_america and global

1980.0

In [58]:
df_game['Year'].nunique

<bound method IndexOpsMixin.nunique of 0        2006.0
1        1985.0
2        2008.0
3        2009.0
4        1996.0
          ...
16593    2002.0
16594    2003.0
16595    2008.0
16596    2010.0
16597    2003.0
Name: Year, Length: 16598, dtype: float64>

In [25]:
df_game['Platform'].unique()

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne', 'GC',
       'WiiU', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

In [26]:
df_game['Genre'].unique()
#12 Genre of game : We can find the total sales for 1 year of games foreach countries and global GENRE BY GENRE

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy'], dtype=object)

In [27]:
yearly_sales = df_game.groupby('Year')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()

print("Total sales year by year for each country:")
print(yearly_sales)

Total sales year by year for each country:
        NA_Sales  EU_Sales  JP_Sales  Other_Sales
Year
1980.0     10.59      0.67      0.00         0.12
1981.0     33.40      1.96      0.00         0.32
1982.0     26.92      1.65      0.00         0.31
1983.0      7.76      0.80      8.10         0.14
1984.0     33.28      2.10     14.27         0.70
1985.0     33.73      4.74     14.56         0.92
1986.0     12.50      2.84     19.81         1.93
1987.0      8.46      1.41     11.63         0.20
1988.0     23.87      6.59     15.76         0.99
1989.0     45.15      8.44     18.36         1.50
1990.0     25.46      7.63     14.88         1.40
1991.0     12.76      3.95     14.78         0.74
1992.0     33.87     11.71     28.91         1.65
1993.0     15.12      4.65     25.33         0.89
1994.0     28.15     14.88     33.99         2.20
1995.0     24.82     14.90     45.75         2.64
1996.0     86.76     47.26     57.44         7.69
1997.0     94.75     48.32     48.87         9.13
1998.0    128.36     66.90     50.04        11.03
1999.0    126.06     62.67     52.34        10.05
2000.0     94.49     52.75     42.77        11.62
2001.0    173.98     94.89     39.86        22.76
2002.0    216.19    109.74     41.76        27.28
2003.0    193.59    103.81     34.20        26.01
2004.0    222.59    107.32     41.65        47.29
2005.0    242.61    121.94     54.28        40.58
2006.0    263.12    129.24     73.73        54.43
2007.0    312.05    160.50     60.29        77.60
2008.0    351.44    184.40     60.26        82.39
2009.0    338.85    191.59     61.89        74.77
2010.0    304.24    176.73     59.49        59.90
2011.0    241.06    167.44     53.04        54.39
2012.0    154.96    118.78     51.74        37.82
2013.0    154.77    125.80     47.59        39.82
2014.0    131.97    125.65     39.46        40.02
2015.0    102.82     97.71     33.72        30.01
2016.0     22.66     26.76     13.70         7.75
2017.0      0.00      0.00      0.05         0.00
2020.0      0.27      0.00      0.00         0.02

In [40]:
import requests
import pandas as pd
# Define the URL for the World Bank API
BASE_URL = "http://api.worldbank.org/v2/country/{}/indicator/NY.GDP.MKTP.CD"
COUNTRIES = {"EUU": "European Union", "NAC": "North America", "JPN": "Japan"}
# Parameters for the API request
params = {
    "date": "1980:2023",  # Date range
    "format": "json",     # Response format
    "per_page": 1000      # Number of results per page
}
# Function to fetch GDP data for a given country code
def fetch_gdp_data(country_code):
    url = BASE_URL.format(country_code)
    response = requests.get(url, params=params)
    data = response.json()
    if response.status_code == 200 and data:
        return data[1]
    else:
        return []
# Fetch data for each country
gdp_data = {}
for code, name in COUNTRIES.items():
    gdp_data[name] = fetch_gdp_data(code)
# Process and convert the data into a DataFrame
all_data = []
for country, data in gdp_data.items():
    for entry in data:
        if 'value' in entry and entry['value'] is not None:
            all_data.append({
                "Country": country,
                "Year": entry['date'],
                "GDP": entry['value']
            })
df = pd.DataFrame(all_data)
# Convert year to integer for better handling
df['Year'] = df['Year'].astype(int)
# Sort the DataFrame by Year
df = df.sort_values(by="Year")
# Display the DataFrame
print(df)
# Save DataFrame to a CSV file
df.to_csv("gdp_data.csv", index=False)

            Country  Year           GDP
131           Japan  1980  1.129377e+12
43   European Union  1980  3.314876e+12
87    North America  1980  3.132697e+12
42   European Union  1981  2.893851e+12
86    North America  1981  3.515027e+12
..              ...   ...           ...
1    European Union  2022  1.676150e+13
89            Japan  2022  4.256411e+12
88            Japan  2023  4.212945e+12
44    North America  2023  2.950930e+13
0    European Union  2023  1.834939e+13

[132 rows x 3 columns]

In [41]:
df.head(50)

            Country  Year           GDP
131           Japan  1980  1.129377e+12
43   European Union  1980  3.314876e+12
87    North America  1980  3.132697e+12
42   European Union  1981  2.893851e+12
86    North America  1981  3.515027e+12
130           Japan  1981  1.245221e+12
41   European Union  1982  2.792073e+12
129           Japan  1982  1.158731e+12
85    North America  1982  3.659222e+12
40   European Union  1983  2.714737e+12
128           Japan  1983  1.270860e+12
84    North America  1983  3.976794e+12
83    North America  1984  4.395317e+12
39   European Union  1984  2.615738e+12
127           Japan  1984  1.345825e+12
38   European Union  1985  2.690006e+12
126           Japan  1985  1.427020e+12
82    North America  1985  4.706205e+12
125           Japan  1986  2.120084e+12
81    North America  1986  4.959811e+12
37   European Union  1986  3.755825e+12
80    North America  1987  5.289646e+12
36   European Union  1987  4.642293e+12
124           Japan  1987  2.580748e+12
79    North America  1988  5.747233e+12
123           Japan  1988  3.125724e+12
35   European Union  1988  5.096307e+12
78    North America  1989  6.210293e+12
122           Japan  1989  3.109455e+12
34   European Union  1989  5.205659e+12
77    North America  1990  6.560812e+12
33   European Union  1990  6.509871e+12
121           Japan  1990  3.185905e+12
32   European Union  1991  6.733633e+12
76    North America  1991  6.772292e+12
120           Japan  1991  3.648066e+12
75    North America  1992  7.116394e+12
119           Japan  1992  3.980703e+12
31   European Union  1992  7.392186e+12
30   European Union  1993  6.751223e+12
74    North America  1993  7.439433e+12
118           Japan  1993  4.536940e+12
29   European Union  1994  7.155503e+12
73    North America  1994  7.869048e+12
117           Japan  1994  4.998798e+12
72    North America  1995  8.247741e+12
116           Japan  1995  5.545564e+12
28   European Union  1995  8.296091e+12
115           Japan  1996  4.923392e+12
71    North America  1996  8.706425e+12

In [45]:
def scientific_to_integer(value):
    return int(value)
#df['GDP'] = df['GDP'].apply(scientific_to_integer)

#print(df)


#changing the GDP value to integer

In [42]:
df = df.pivot(index='Year', columns='Country', values='GDP')

In [43]:
df

Country  European Union         Japan  North America
Year
1980       3.314876e+12  1.129377e+12   3.132697e+12
1981       2.893851e+12  1.245221e+12   3.515027e+12
1982       2.792073e+12  1.158731e+12   3.659222e+12
1983       2.714737e+12  1.270860e+12   3.976794e+12
1984       2.615738e+12  1.345825e+12   4.395317e+12
1985       2.690006e+12  1.427020e+12   4.706205e+12
1986       3.755825e+12  2.120084e+12   4.959811e+12
1987       4.642293e+12  2.580748e+12   5.289646e+12
1988       5.096307e+12  3.125724e+12   5.747233e+12
1989       5.205659e+12  3.109455e+12   6.210293e+12
1990       6.509871e+12  3.185905e+12   6.560812e+12
1991       6.733633e+12  3.648066e+12   6.772292e+12
1992       7.392186e+12  3.980703e+12   7.116394e+12
1993       6.751223e+12  4.536940e+12   7.439433e+12
1994       7.155503e+12  4.998798e+12   7.869048e+12
1995       8.296091e+12  5.545564e+12   8.247741e+12
1996       8.431591e+12  4.923392e+12   8.706425e+12
1997       7.733844e+12  4.492449e+12   9.235472e+12
1998       7.969881e+12  4.098363e+12   9.699948e+12
1999       7.925845e+12  4.635982e+12   1.031291e+13
2000       7.276391e+12  4.968359e+12   1.099921e+13
2001       7.393612e+12  4.374712e+12   1.132459e+13
2002       8.083520e+12  4.182846e+12   1.169369e+13
2003       9.932135e+12  4.519562e+12   1.235618e+13
2004       1.141890e+13  4.893116e+12   1.324837e+13
2005       1.191007e+13  4.831467e+12   1.421717e+13
2006       1.271264e+13  4.601663e+12   1.514099e+13
2007       1.472752e+13  4.579751e+12   1.594982e+13
2008       1.629539e+13  5.106679e+12   1.632983e+13
2009       1.476284e+13  5.289493e+12   1.585935e+13
2010       1.455612e+13  5.759072e+12   1.667295e+13
2011       1.576516e+13  6.233147e+12   1.739937e+13
2012       1.464163e+13  6.272363e+12   1.808871e+13
2013       1.529485e+13  5.212328e+12   1.873375e+13
2014       1.565137e+13  4.896994e+12   1.942030e+13
2015       1.355390e+13  4.444931e+12   1.985818e+13
2016       1.388883e+13  5.003678e+12   2.033981e+13
2017       1.476588e+13  4.930837e+12   2.126851e+13
2018       1.598145e+13  5.040881e+12   2.238907e+13
2019       1.569405e+13  5.117994e+12   2.327254e+13
2020       1.538142e+13  5.055587e+12   2.298552e+13
2021       1.731513e+13  5.034621e+12   2.560879e+13
2022       1.676150e+13  4.256411e+12   2.791342e+13
2023       1.834939e+13  4.212945e+12   2.950930e+13

In [51]:
yearly_sales

        NA_Sales  EU_Sales  JP_Sales  Other_Sales
Year
1980.0     10.59      0.67      0.00         0.12
1981.0     33.40      1.96      0.00         0.32
1982.0     26.92      1.65      0.00         0.31
1983.0      7.76      0.80      8.10         0.14
1984.0     33.28      2.10     14.27         0.70
1985.0     33.73      4.74     14.56         0.92
1986.0     12.50      2.84     19.81         1.93
1987.0      8.46      1.41     11.63         0.20
1988.0     23.87      6.59     15.76         0.99
1989.0     45.15      8.44     18.36         1.50
1990.0     25.46      7.63     14.88         1.40
1991.0     12.76      3.95     14.78         0.74
1992.0     33.87     11.71     28.91         1.65
1993.0     15.12      4.65     25.33         0.89
1994.0     28.15     14.88     33.99         2.20
1995.0     24.82     14.90     45.75         2.64
1996.0     86.76     47.26     57.44         7.69
1997.0     94.75     48.32     48.87         9.13
1998.0    128.36     66.90     50.04        11.03
1999.0    126.06     62.67     52.34        10.05
2000.0     94.49     52.75     42.77        11.62
2001.0    173.98     94.89     39.86        22.76
2002.0    216.19    109.74     41.76        27.28
2003.0    193.59    103.81     34.20        26.01
2004.0    222.59    107.32     41.65        47.29
2005.0    242.61    121.94     54.28        40.58
2006.0    263.12    129.24     73.73        54.43
2007.0    312.05    160.50     60.29        77.60
2008.0    351.44    184.40     60.26        82.39
2009.0    338.85    191.59     61.89        74.77
2010.0    304.24    176.73     59.49        59.90
2011.0    241.06    167.44     53.04        54.39
2012.0    154.96    118.78     51.74        37.82
2013.0    154.77    125.80     47.59        39.82
2014.0    131.97    125.65     39.46        40.02
2015.0    102.82     97.71     33.72        30.01
2016.0     22.66     26.76     13.70         7.75
2017.0      0.00      0.00      0.05         0.00
2020.0      0.27      0.00      0.00         0.02

In [52]:
yearly_sales.index  = yearly_sales.index.astype(int)
#Converting the indexes from float to intiger

In [53]:
yearly_sales

      NA_Sales  EU_Sales  JP_Sales  Other_Sales
Year
1980     10.59      0.67      0.00         0.12
1981     33.40      1.96      0.00         0.32
1982     26.92      1.65      0.00         0.31
1983      7.76      0.80      8.10         0.14
1984     33.28      2.10     14.27         0.70
1985     33.73      4.74     14.56         0.92
1986     12.50      2.84     19.81         1.93
1987      8.46      1.41     11.63         0.20
1988     23.87      6.59     15.76         0.99
1989     45.15      8.44     18.36         1.50
1990     25.46      7.63     14.88         1.40
1991     12.76      3.95     14.78         0.74
1992     33.87     11.71     28.91         1.65
1993     15.12      4.65     25.33         0.89
1994     28.15     14.88     33.99         2.20
1995     24.82     14.90     45.75         2.64
1996     86.76     47.26     57.44         7.69
1997     94.75     48.32     48.87         9.13
1998    128.36     66.90     50.04        11.03
1999    126.06     62.67     52.34        10.05
2000     94.49     52.75     42.77        11.62
2001    173.98     94.89     39.86        22.76
2002    216.19    109.74     41.76        27.28
2003    193.59    103.81     34.20        26.01
2004    222.59    107.32     41.65        47.29
2005    242.61    121.94     54.28        40.58
2006    263.12    129.24     73.73        54.43
2007    312.05    160.50     60.29        77.60
2008    351.44    184.40     60.26        82.39
2009    338.85    191.59     61.89        74.77
2010    304.24    176.73     59.49        59.90
2011    241.06    167.44     53.04        54.39
2012    154.96    118.78     51.74        37.82
2013    154.77    125.80     47.59        39.82
2014    131.97    125.65     39.46        40.02
2015    102.82     97.71     33.72        30.01
2016     22.66     26.76     13.70         7.75
2017      0.00      0.00      0.05         0.00
2020      0.27      0.00      0.00         0.02

In [55]:
#Merging this two data set together
merged_df = pd.concat([yearly_sales, df], axis=1)

In [56]:
merged_df

,NA_Sales,EU_Sales,JP_Sales,Other_Sales,European Union,Japan,North America
Year,,,,,,,
1980,10.59,0.67,0.00,0.12,3.314876e+12,1.129377e+12,3.132697e+12
1981,33.40,1.96,0.00,0.32,2.893851e+12,1.245221e+12,3.515027e+12
1982,26.92,1.65,0.00,0.31,2.792073e+12,1.158731e+12,3.659222e+12
1983,7.76,0.80,8.10,0.14,2.714737e+12,1.270860e+12,3.976794e+12
1984,33.28,2.10,14.27,0.70,2.615738e+12,1.345825e+12,4.395317e+12
1985,33.73,4.74,14.56,0.92,2.690006e+12,1.427020e+12,4.706205e+12
1986,12.50,2.84,19.81,1.93,3.755825e+12,2.120084e+12,4.959811e+12
1987,8.46,1.41,11.63,0.20,4.642293e+12,2.580748e+12,5.289646e+12
1988,23.87,6.59,15.76,0.99,5.096307e+12,3.125724e+12,5.747233e+12
1989,45.15,8.44,18.36,1.50,5.205659e+12,3.109455e+12,6.210293e+12
1990,25.46,7.63,14.88,1.40,6.509871e+12,3.185905e+12,6.560812e+12
1991,12.76,3.95,14.78,0.74,6.733633e+12,3.648066e+12,6.772292e+12
1992,33.87,11.71,28.91,1.65,7.392186e+12,3.980703e+12,7.116394e+12
1993,15.12,4.65,25.33,0.89,6.751223e+12,4.536940e+12,7.439433e+12
1994,28.15,14.88,33.99,2.20,7.155503e+12,4.998798e+12,7.869048e+12
1995,24.82,14.90,45.75,2.64,8.296091e+12,5.545564e+12,8.247741e+12
1996,86.76,47.26,57.44,7.69,8.431591e+12,4.923392e+12,8.706425e+12
1997,94.75,48.32,48.87,9.13,7.733844e+12,4.492449e+12,9.235472e+12
1998,128.36,66.90,50.04,11.03,7.969881e+12,4.098363e+12,9.699948e+12
1999,126.06,62.67,52.34,10.05,7.925845e+12,4.635982e+12,1.031291e+13
2000,94.49,52.75,42.77,11.62,7.276391e+12,4.968359e+12,1.099921e+13
2001,173.98,94.89,39.86,22.76,7.393612e+12,4.374712e+12,1.132459e+13
2002,216.19,109.74,41.76,27.28,8.083520e+12,4.182846e+12,1.169369e+13
2003,193.59,103.81,34.20,26.01,9.932135e+12,4.519562e+12,1.235618e+13
2004,222.59,107.32,41.65,47.29,1.141890e+13,4.893116e+12,1.324837e+13
2005,242.61,121.94,54.28,40.58,1.191007e+13,4.831467e+12,1.421717e+13
2006,263.12,129.24,73.73,54.43,1.271264e+13,4.601663e+12,1.514099e+13
2007,312.05,160.50,60.29,77.60,1.472752e+13,4.579751e+12,1.594982e+13
2008,351.44,184.40,60.26,82.39,1.629539e+13,5.106679e+12,1.632983e+13
2009,338.85,191.59,61.89,74.77,1.476284e+13,5.289493e+12,1.585935e+13
2010,304.24,176.73,59.49,59.90,1.455612e+13,5.759072e+12,1.667295e+13
2011,241.06,167.44,53.04,54.39,1.576516e+13,6.233147e+12,1.739937e+13
2012,154.96,118.78,51.74,37.82,1.464163e+13,6.272363e+12,1.808871e+13
2013,154.77,125.80,47.59,39.82,1.529485e+13,5.212328e+12,1.873375e+13
2014,131.97,125.65,39.46,40.02,1.565137e+13,4.896994e+12,1.942030e+13
2015,102.82,97.71,33.72,30.01,1.355390e+13,4.444931e+12,1.985818e+13
2016,22.66,26.76,13.70,7.75,1.388883e+13,5.003678e+12,2.033981e+13
2017,0.00,0.00,0.05,0.00,1.476588e+13,4.930837e+12,2.126851e+13
2020,0.27,0.00,0.00,0.02,1.538142e+13,5.055587e+12,2.298552e+13
2018,NaN,NaN,NaN,NaN,1.598145e+13,5.040881e+12,2.238907e+13
2019,NaN,NaN,NaN,NaN,1.569405e+13,5.117994e+12,2.327254e+13
2021,NaN,NaN,NaN,NaN,1.731513e+13,5.034621e+12,2.560879e+13
2022,NaN,NaN,NaN,NaN,1.676150e+13,4.256411e+12,2.791342e+13
2023,NaN,NaN,NaN,NaN,1.834939e+13,4.212945e+12,2.950930e+13

In [60]:
#We can see that after 2015, there is a huge dropping by sales and than even they drop to 0 sell
#which is imposssible and that is giving us NAN values end of the data. We are asumming that data is not meaningful after 
#2015 and we are deleting this part.


merged_df =merged_df[merged_df.index <= 2016]

print(merged_df)

      NA_Sales  EU_Sales  JP_Sales  Other_Sales  European Union         Japan  \
Year
1980     10.59      0.67      0.00         0.12    3.314876e+12  1.129377e+12
1981     33.40      1.96      0.00         0.32    2.893851e+12  1.245221e+12
1982     26.92      1.65      0.00         0.31    2.792073e+12  1.158731e+12
1983      7.76      0.80      8.10         0.14    2.714737e+12  1.270860e+12
1984     33.28      2.10     14.27         0.70    2.615738e+12  1.345825e+12
1985     33.73      4.74     14.56         0.92    2.690006e+12  1.427020e+12
1986     12.50      2.84     19.81         1.93    3.755825e+12  2.120084e+12
1987      8.46      1.41     11.63         0.20    4.642293e+12  2.580748e+12
1988     23.87      6.59     15.76         0.99    5.096307e+12  3.125724e+12
1989     45.15      8.44     18.36         1.50    5.205659e+12  3.109455e+12
1990     25.46      7.63     14.88         1.40    6.509871e+12  3.185905e+12
1991     12.76      3.95     14.78         0.74    6.733633e+12  3.648066e+12
1992     33.87     11.71     28.91         1.65    7.392186e+12  3.980703e+12
1993     15.12      4.65     25.33         0.89    6.751223e+12  4.536940e+12
1994     28.15     14.88     33.99         2.20    7.155503e+12  4.998798e+12
1995     24.82     14.90     45.75         2.64    8.296091e+12  5.545564e+12
1996     86.76     47.26     57.44         7.69    8.431591e+12  4.923392e+12
1997     94.75     48.32     48.87         9.13    7.733844e+12  4.492449e+12
1998    128.36     66.90     50.04        11.03    7.969881e+12  4.098363e+12
1999    126.06     62.67     52.34        10.05    7.925845e+12  4.635982e+12
2000     94.49     52.75     42.77        11.62    7.276391e+12  4.968359e+12
2001    173.98     94.89     39.86        22.76    7.393612e+12  4.374712e+12
2002    216.19    109.74     41.76        27.28    8.083520e+12  4.182846e+12
2003    193.59    103.81     34.20        26.01    9.932135e+12  4.519562e+12
2004    222.59    107.32     41.65        47.29    1.141890e+13  4.893116e+12
2005    242.61    121.94     54.28        40.58    1.191007e+13  4.831467e+12
2006    263.12    129.24     73.73        54.43    1.271264e+13  4.601663e+12
2007    312.05    160.50     60.29        77.60    1.472752e+13  4.579751e+12
2008    351.44    184.40     60.26        82.39    1.629539e+13  5.106679e+12
2009    338.85    191.59     61.89        74.77    1.476284e+13  5.289493e+12
2010    304.24    176.73     59.49        59.90    1.455612e+13  5.759072e+12
2011    241.06    167.44     53.04        54.39    1.576516e+13  6.233147e+12
2012    154.96    118.78     51.74        37.82    1.464163e+13  6.272363e+12
2013    154.77    125.80     47.59        39.82    1.529485e+13  5.212328e+12
2014    131.97    125.65     39.46        40.02    1.565137e+13  4.896994e+12
2015    102.82     97.71     33.72        30.01    1.355390e+13  4.444931e+12
2016     22.66     26.76     13.70         7.75    1.388883e+13  5.003678e+12

      North America
Year
1980   3.132697e+12
1981   3.515027e+12
1982   3.659222e+12
1983   3.976794e+12
1984   4.395317e+12
1985   4.706205e+12
1986   4.959811e+12
1987   5.289646e+12
1988   5.747233e+12
1989   6.210293e+12
1990   6.560812e+12
1991   6.772292e+12
1992   7.116394e+12
1993   7.439433e+12
1994   7.869048e+12
1995   8.247741e+12
1996   8.706425e+12
1997   9.235472e+12
1998   9.699948e+12
1999   1.031291e+13
2000   1.099921e+13
2001   1.132459e+13
2002   1.169369e+13
2003   1.235618e+13
2004   1.324837e+13
2005   1.421717e+13
2006   1.514099e+13
2007   1.594982e+13
2008   1.632983e+13
2009   1.585935e+13
2010   1.667295e+13
2011   1.739937e+13
2012   1.808871e+13
2013   1.873375e+13
2014   1.942030e+13
2015   1.985818e+13
2016   2.033981e+13

In [64]:
new_column_names = {
    "European Union" : "EU GDP" ,
    "Japan" :"JAPAN GDP",
    "North America" : "NA GDP" 
}

In [68]:
merged_df= merged_df.rename(columns=new_column_names)

In [69]:
merged_df

,NA_Sales,EU_Sales,JP_Sales,Other_Sales,EU GDP,JAPAN GDP,NA GDP
Year,,,,,,,
1980,10.59,0.67,0.00,0.12,3.314876e+12,1.129377e+12,3.132697e+12
1981,33.40,1.96,0.00,0.32,2.893851e+12,1.245221e+12,3.515027e+12
1982,26.92,1.65,0.00,0.31,2.792073e+12,1.158731e+12,3.659222e+12
1983,7.76,0.80,8.10,0.14,2.714737e+12,1.270860e+12,3.976794e+12
1984,33.28,2.10,14.27,0.70,2.615738e+12,1.345825e+12,4.395317e+12
1985,33.73,4.74,14.56,0.92,2.690006e+12,1.427020e+12,4.706205e+12
1986,12.50,2.84,19.81,1.93,3.755825e+12,2.120084e+12,4.959811e+12
1987,8.46,1.41,11.63,0.20,4.642293e+12,2.580748e+12,5.289646e+12
1988,23.87,6.59,15.76,0.99,5.096307e+12,3.125724e+12,5.747233e+12
1989,45.15,8.44,18.36,1.50,5.205659e+12,3.109455e+12,6.210293e+12
1990,25.46,7.63,14.88,1.40,6.509871e+12,3.185905e+12,6.560812e+12
1991,12.76,3.95,14.78,0.74,6.733633e+12,3.648066e+12,6.772292e+12
1992,33.87,11.71,28.91,1.65,7.392186e+12,3.980703e+12,7.116394e+12
1993,15.12,4.65,25.33,0.89,6.751223e+12,4.536940e+12,7.439433e+12
1994,28.15,14.88,33.99,2.20,7.155503e+12,4.998798e+12,7.869048e+12
1995,24.82,14.90,45.75,2.64,8.296091e+12,5.545564e+12,8.247741e+12
1996,86.76,47.26,57.44,7.69,8.431591e+12,4.923392e+12,8.706425e+12
1997,94.75,48.32,48.87,9.13,7.733844e+12,4.492449e+12,9.235472e+12
1998,128.36,66.90,50.04,11.03,7.969881e+12,4.098363e+12,9.699948e+12
1999,126.06,62.67,52.34,10.05,7.925845e+12,4.635982e+12,1.031291e+13
2000,94.49,52.75,42.77,11.62,7.276391e+12,4.968359e+12,1.099921e+13
2001,173.98,94.89,39.86,22.76,7.393612e+12,4.374712e+12,1.132459e+13
2002,216.19,109.74,41.76,27.28,8.083520e+12,4.182846e+12,1.169369e+13
2003,193.59,103.81,34.20,26.01,9.932135e+12,4.519562e+12,1.235618e+13
2004,222.59,107.32,41.65,47.29,1.141890e+13,4.893116e+12,1.324837e+13
2005,242.61,121.94,54.28,40.58,1.191007e+13,4.831467e+12,1.421717e+13
2006,263.12,129.24,73.73,54.43,1.271264e+13,4.601663e+12,1.514099e+13
2007,312.05,160.50,60.29,77.60,1.472752e+13,4.579751e+12,1.594982e+13
2008,351.44,184.40,60.26,82.39,1.629539e+13,5.106679e+12,1.632983e+13
2009,338.85,191.59,61.89,74.77,1.476284e+13,5.289493e+12,1.585935e+13
2010,304.24,176.73,59.49,59.90,1.455612e+13,5.759072e+12,1.667295e+13
2011,241.06,167.44,53.04,54.39,1.576516e+13,6.233147e+12,1.739937e+13
2012,154.96,118.78,51.74,37.82,1.464163e+13,6.272363e+12,1.808871e+13
2013,154.77,125.80,47.59,39.82,1.529485e+13,5.212328e+12,1.873375e+13
2014,131.97,125.65,39.46,40.02,1.565137e+13,4.896994e+12,1.942030e+13
2015,102.82,97.71,33.72,30.01,1.355390e+13,4.444931e+12,1.985818e+13
2016,22.66,26.76,13.70,7.75,1.388883e+13,5.003678e+12,2.033981e+13

DAY2 = SEBASTIANS PART

In [1]:
data = data[data['Year'] <= 2015]
# Group by 'Year' and 'Genre' and count the occurrences
genre_trends = data.groupby(['Year', 'Genre']).size().unstack().fillna(0)
# Identify the top 5 genres based on total counts
top_genres = genre_trends.sum().nlargest(5).index
# Filter to include only the top 5 genres
genre_trends_top5 = genre_trends[top_genres]
# Optionally, convert counts to proportions for each year
genre_proportions_top5 = genre_trends_top5.div(genre_trends_top5.sum(axis=1), axis=0)
# Plotting the trends for the top 5 genres
plt.figure(figsize=(14, 7))
for genre in genre_trends_top5.columns:
    plt.plot(genre_trends_top5.index, genre_trends_top5[genre], label=genre)
plt.title('Trends in Video Game Genres Over Time (up to 2015)')
plt.xlabel('Year')
plt.ylabel('Number of Games')
plt.legend(title='Genre')
plt.show()
# Plotting the proportions for the top 5 genres
#plt.figure(figsize=(14, 7))
#for genre in genre_proportions_top5.columns:
    #plt.plot(genre_proportions_top5.index, genre_proportions_top5[genre], label=genre)
#plt.title('Proportions of Video Game Genres Over Time (up to 2015)')
#plt.xlabel('Year')
#plt.ylabel('Proportion of Games')
#plt.legend(title='Genre')
#plt.show()
4:39
sales_trends = data.groupby(['Year', 'Genre'])[['NA_Sales', 'EU_Sales', 'JP_Sales']].sum()
# Create a DataFrame that sums sales across all years for each genre
total_sales_per_genre = sales_trends.groupby('Genre').sum()
# Sum the sales across all regions to determine the top genres globally
top_genres = total_sales_per_genre.sum(axis=1).nlargest(5).index
# Filter to include only the top 5 genres
sales_trends_top5 = sales_trends.loc[(slice(None), top_genres), :]
# Plotting the trends for the top 5 genres in each region
plt.figure(figsize=(18, 9))
for region in ['NA_Sales', 'EU_Sales', 'JP_Sales']:
    plt.subplot(1, 3, {'NA_Sales': 1, 'EU_Sales': 2, 'JP_Sales': 3}[region])
    for genre in top_genres:
        plt.plot(sales_trends_top5.xs(genre, level='Genre').index,
                 sales_trends_top5.xs(genre, level='Genre')[region],
                 label=genre)
    plt.title(f'Trends in {region[:-6]} Sales by Genre (up to 2015)')
    plt.xlabel('Year')
    plt.ylabel('Sales (Millions)')
    plt.legend(title='Genre')
plt.tight_layout()
plt.show()

SyntaxError: illegal target for annotation (4062415902.py, line 28)